/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajo.aulico;

import Clases.Empleado;
import Clases.Empresa;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author pablo
 */
public class TrabajoAulico extends javax.swing.JFrame {
   

    /**
     * Creates new form hjkhj
     */
    public TrabajoAulico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jlDocumento = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jlSueldo = new javax.swing.JLabel();
        jlEmpresas = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        jtfDocumento = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        jtfSueldo = new javax.swing.JTextField();
        jcbEmpresa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jlRazonSocial = new javax.swing.JLabel();
        jlCuit = new javax.swing.JLabel();
        jtfRazonSocial = new javax.swing.JTextField();
        jtfCuit = new javax.swing.JTextField();
        jbCrearEmpresa = new javax.swing.JButton();
        jlTitulo2 = new javax.swing.JLabel();
        jlTitulo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(204, 153, 0));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jlDocumento.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlDocumento.setText("Documento");

        jlNombre.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlApellido.setText("Apellido");

        jlCategoria.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlCategoria.setText("Categoria");

        jlSueldo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlSueldo.setText("Sueldo");

        jlEmpresas.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlEmpresas.setText("Empresas -->");

        jbGuardar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbMostrar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jbMostrar.setText("Mostrar Empleados");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GERENTE", "JEFE", "ADMINISTRATIVO", "SUPERVISOR", "OPERARIO" }));
        jcbCategoria.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jbMostrar))
                            .addComponent(jlCategoria)
                            .addComponent(jlApellido)
                            .addComponent(jlNombre))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEmpresas)
                            .addComponent(jlSueldo)
                            .addComponent(jlDocumento))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDocumento)
                            .addComponent(jcbEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfSueldo)
                            .addComponent(jtfNombre)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlDocumento)
                                    .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jlNombre))
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlApellido))
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategoria)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSueldo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEmpresas))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbMostrar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jlRazonSocial.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlRazonSocial.setText("Razon Social");

        jlCuit.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlCuit.setText("C.U.I.T");

        jbCrearEmpresa.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jbCrearEmpresa.setText("Crear Empresa");
        jbCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRazonSocial)
                    .addComponent(jlCuit))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfRazonSocial)
                    .addComponent(jtfCuit, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jbCrearEmpresa)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlRazonSocial)
                    .addComponent(jtfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCuit)
                    .addComponent(jtfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbCrearEmpresa)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jlTitulo2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jlTitulo2.setText("Ingrese datos");

        jlTitulo1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jlTitulo1.setText("Ingrese datos");

        jMenu1.setText("Empleado");
        jMenu1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empresa");
        jMenu2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu7.setText("Sueldo");
        jMenu7.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlTitulo1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo2)
                    .addComponent(jlTitulo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearEmpresaActionPerformed
        // TODO add your handling code here:
        try{
        String razon=jtfRazonSocial.getText();
        int cuit=Integer.parseInt(jtfCuit.getText());        
        Empresa empNuevo= new Empresa(razon,cuit);
        if(razon.isEmpty()&&jtfCuit.getText()==null){
            JOptionPane.showMessageDialog(this,"Llene los Campos");
            return;
        }        
        jcbEmpresa.addItem(empNuevo);
        limpiarEmpresa();       
        }catch(NumberFormatException v){
            JOptionPane.showMessageDialog(this,"Ingrese solo numeros");
        }       
    }//GEN-LAST:event_jbCrearEmpresaActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
      try{
        int doc=Integer.parseInt(jtfDocumento.getText());
        String nom=jtfNombre.getText();
        String ape=jtfApellido.getText();
        String cat=jcbCategoria.getSelectedItem().toString();
        double sue=Double.parseDouble(jtfSueldo.getText()); 
        Empresa empSelec=(Empresa)jcbEmpresa.getSelectedItem();
        Empleado empleado=new Empleado(doc,nom,ape,cat,sue,empSelec);
        if(nom.isEmpty()||ape.isEmpty()||cat.isEmpty()){
            JOptionPane.showMessageDialog(this,"Debe llenar los campos!!");
            return;
        }        
        empSelec.agregarEmpleado(empleado);          
        limpiarEmpleado();
        }catch(NumberFormatException v){
            if(jtfDocumento.getSelectedText()==null)
          JOptionPane.showMessageDialog(this,"Llene los campos de Documento  Sueldo");
        }catch(NullPointerException f){
            if(jcbCategoria.getSelectedItem()==null){
                JOptionPane.showMessageDialog(this,"Selecione una Categoria");
            } else if(jcbEmpresa.getSelectedItem()==null){
                JOptionPane.showMessageDialog(this,"Seleccione una Empresa");
            }            
        }            
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
         try{
        Empresa Selec=(Empresa)jcbEmpresa.getSelectedItem();
        ArrayList<Empleado> empleados=Selec.mostrarEmpleado();
        
        for (Empleado emplea : empleados){
            JOptionPane.showMessageDialog(this,emplea.getCategoria()+": "+emplea.getNombre()+" "+emplea.getApellido());            
        }
        }catch(RuntimeException v){
            JOptionPane.showMessageDialog(this,"Selecione una Empresa!!");
        }
        jcbEmpresa.setSelectedIndex(-1);               
    }//GEN-LAST:event_jbMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        Color color=new Color(209,242,235);
        UIManager.put("control",color);
        UIManager.put("nimbusSelectionBackground",new Color(118,215,196));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajoAulico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajoAulico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajoAulico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajoAulico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrabajoAulico().setVisible(true);
            }
        });
    }
    
    private void limpiarEmpleado(){
        jtfDocumento.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
        jcbCategoria.setSelectedIndex(-1);
        jtfSueldo.setText("");
        jcbEmpresa.setSelectedIndex(-1);
        
    }
    
    private void limpiarEmpresa(){
        jtfRazonSocial.setText("");
        jtfCuit.setText("");
    }
    
    private void activa(){
        jbGuardar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCrearEmpresa;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<Empresa> jcbEmpresa;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlCuit;
    private javax.swing.JLabel jlDocumento;
    private javax.swing.JLabel jlEmpresas;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlRazonSocial;
    private javax.swing.JLabel jlSueldo;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCuit;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRazonSocial;
    private javax.swing.JTextField jtfSueldo;
    // End of variables declaration//GEN-END:variables
}
